export const SET_USER_INFO = 'SET_USER_INFO';
export const ENABLE_LOADING = 'ENABLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED';

export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
